version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "sceneformux/build.gradle" }}-{{ checksum  "sceneformux/ux/build.gradle" }}
    - run:
        working_directory: ~/code/sceneformux
        name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
        command: sudo chmod +x ./gradlew
    - run:
        working_directory: ~/code/sceneformux
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        working_directory: ~/code/sceneformux
        paths:
        - ~/.gradle
        key: jars-{{ checksum "sceneformux/build.gradle" }}-{{ checksum  "sceneformux/ux/build.gradle" }}
    - run:
        name: Git LFS
        command: |
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs pull
    - run:
        working_directory: ~/code/sceneformux
        name: Run Build
        command: ./gradlew lint assemble
    - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
        path: sceneformux/ux/build/reports
        destination: sceneformux/ux/reports
    # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
